# Generated by Django 5.2.9 on 2026-04-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('latitude', models.CharField()),
                ('longitude', models.CharField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'location',
            },
        ),
    ]
